version: '3'

services:
  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: brick
      MONGO_INITDB_ROOT_PASSWORD: brick
      MONGO_INITDB_DATABASE: brick
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - ./data:/data/db

  redis:
    image: redis
    container_name: redis
    restart: always
    ports:
      - '6379:6379'
